set(CPACK_GENERATOR "DEB")
set(CPACK_SOURCE_GENERATOR "TGZ")

set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Yoonyoung (Jamie) Cho")

set(CPACK_PACKAGE_VERSION
    "${CHO_VERSION_MAJOR}.${CHO_VERSION_MINOR}.${CHO_VERSION_PATCH}")
set(CPACK_PACKAGE_VERSION_MAJOR "${CHO_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${CHO_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${CHO_VERSION_PATCH}")

set(CPACK_PACKAGE_DESCRIPTION_FILE "${PROJECT_SOURCE_DIR}/README.md")
set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${PROJECT_SOURCE_DIR}/README.md")
set(CPACK_RESOURCE_FILE_WELCOME "${PROJECT_SOURCE_DIR}/README.md")
set(CPACK_PACKAGING_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

set(CPACK_SOURCE_IGNORE_FILES
    "${PROJECT_SOURCE_DIR}/build/;${PROJECT_SOURCE_DIR}/install/;${CMAKE_SOURCE_DIR}/.git/")
