SET(CU_VERSION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/cho_util/core/include/cho_util/core/version.hpp")
file(STRINGS "${CU_VERSION_FILE}" CU_VERSION_PARTS REGEX "#define CU_VERSION_[A-Z]+[ ]+" )

string(REGEX REPLACE ".+CU_VERSION_MAJOR[ ]+([0-9]+).*" "\\1" CU_VERSION_MAJOR "${CU_VERSION_PARTS}")
string(REGEX REPLACE ".+CU_VERSION_MINOR[ ]+([0-9]+).*" "\\1" CU_VERSION_MINOR "${CU_VERSION_PARTS}")
string(REGEX REPLACE ".+CU_VERSION_PATCH[ ]+([0-9]+).*" "\\1" CU_VERSION_PATCH "${CU_VERSION_PARTS}")
